CREATE TABLE bddemo.TBPERSONA 
(NOMBRE CHAR (30), 
APELLIDO CHAR (30), 
CEDULA CHAR (10), 
FECHANACIMIENTO CHAR (10))    

ALTER TABLE bddemo.TBPERSONA 
ADD Imagen BLOB NuLL;

select * from bddemo.TBPERSONA

DROP TABLE bddemo.TBPERSONA
 
